# Generated by Django 2.2 on 2022-01-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20220105_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
